name: boli
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_plus: ^4.0.0
  local_auth: ^2.1.6
  page_transition: "^2.0.9"
  fl_chart: ^0.63.0
  money_formatter: ^0.0.4
  camera: ^0.10.5+2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DM Sans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
