// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByolfupCMnjTpBuKU5Pq00Sb5L43vtZf0',
    appId: '1:983109549401:web:56607810e19ae8da51e048',
    messagingSenderId: '983109549401',
    projectId: 'boli-digital-bank',
    authDomain: 'boli-digital-bank.firebaseapp.com',
    storageBucket: 'boli-digital-bank.appspot.com',
    measurementId: 'G-YX4HEKTC2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwbUwXIR02voiQU8YAlB4qU8lmUYjrCVQ',
    appId: '1:983109549401:android:4bd2aac87149f6b751e048',
    messagingSenderId: '983109549401',
    projectId: 'boli-digital-bank',
    storageBucket: 'boli-digital-bank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpo0luNRJeI46ZW7NJ-Qm3N_S5L7rmynM',
    appId: '1:983109549401:ios:4de69e978d509a0a51e048',
    messagingSenderId: '983109549401',
    projectId: 'boli-digital-bank',
    storageBucket: 'boli-digital-bank.appspot.com',
    iosBundleId: 'com.example.boliDigitalBank',
  );
}
